FINISH  {[[{"root",
            [{"t1","content1"},
             {"t2","content2"},
             {"t3","content3"},
             {"parent",
              [{"c1","child one"},
               {"parent2",
                [{"list",[{"t0","el1"},{"t0","el2"},{"t0","el3"}]},
                 {"c1",undefined},
                 {"c2","child2 two"}]},
               {"c2","child two"}]},
             {"t4","content4"},
             {"t4",undefined}]}]],
         []}
